# Generated by Django 2.2.14 on 2020-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('V', 'Veg Pizza'), ('NV', 'Non Veg Pizza'), ('B', 'Beverages'), ('S', 'Sides')], max_length=2),
        ),
    ]
